language: node_js
node_js:
  - "8.12.0"
services:
  - mongodb
before_script:
  - sleep 25
  - mongo mydb_test_population --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
after_success: 
  - npm run coveralls
  - npm runserver:coverage 